In [1]:
#installing dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
#models
from sklearn.linear_model import LinearRegression, LogisticRegression
#metrics
from sklearn import metrics

In [2]:
#reading the data
train_data=pd.read_csv(r"C:\Users\thoka\Desktop\Bank-Marketing\Datasets\trainset.csv")

In [3]:
# Correcting the drop method by using a flat list of column names
train_data.drop(columns=["job", "marital", "contact", "month", "day_of_week", "poutcome"])
train_data.head()

age           job   marital            education housing loan    contact  \
0   41   blue-collar  divorced             basic.4y     yes   no  telephone   
1   49  entrepreneur   married    university.degree     yes   no  telephone   
2   49    technician   married             basic.9y      no   no  telephone   
3   41    technician   married  professional.course     yes   no  telephone   
4   45   blue-collar   married             basic.9y     yes   no  telephone   

  month day_of_week  duration  campaign  pdays     poutcome Subscribed  
0   may         mon      1575         1    999  nonexistent        yes  
1   may         mon      1042         1    999  nonexistent        yes  
2   may         mon      1467         1    999  nonexistent        yes  
3   may         mon       579         1    999  nonexistent        yes  
4   may         mon       461         1    999  nonexistent        yes

In [4]:
#converting categories into numerics 
train_data["housing"]=train_data["housing"].astype("category")
train_data["housing"]=train_data["housing"].cat.codes

train_data["loan"]=train_data["loan"].astype("category")
train_data["loan"]=train_data["loan"].cat.codes

train_data["Subscribed"]=train_data["Subscribed"].astype("category")
train_data["Subscribed"]=train_data["Subscribed"].cat.codes

In [9]:
train_data.tail()

age          job   marital            education  housing  loan  \
29266   49       admin.   married              unknown        0     0   
29267   34   management    single    university.degree        1     1   
29268   29   technician    single  professional.course        0     0   
29269   57  blue-collar   married             basic.9y        0     2   
29270   45     services  divorced          high.school        2     0   

         contact month day_of_week  duration  campaign  pdays     poutcome  \
29266   cellular   nov         fri       288         1    999      failure   
29267  telephone   nov         fri       114         5    999  nonexistent   
29268   cellular   nov         fri       161         3    999  nonexistent   
29269   cellular   nov         fri       150         2    999  nonexistent   
29270   cellular   nov         fri       120         2    999  nonexistent   

       Subscribed  
29266           0  
29267           0  
29268           0  
29269           0  
29270           0

In [11]:
train_data.isnull().sum()

age            0
job            0
marital        0
education      0
housing        0
loan           0
contact        0
month          0
day_of_week    0
duration       0
campaign       0
pdays          0
poutcome       0
Subscribed     0
dtype: int64

In [13]:
train_data.columns

Index(['age', 'job', 'marital', 'education', 'housing', 'loan', 'contact',
       'month', 'day_of_week', 'duration', 'campaign', 'pdays', 'poutcome',
       'Subscribed'],
      dtype='object')

In [15]:

train_data.drop(columns=["job", "marital", "contact", "month", "day_of_week", "poutcome","education"], inplace=True)
train_data.head()

age  housing  loan  duration  campaign  pdays  Subscribed
0   41        2     0      1575         1    999           1
1   49        2     0      1042         1    999           1
2   49        0     0      1467         1    999           1
3   41        2     0       579         1    999           1
4   45        2     0       461         1    999           1

In [17]:
train_data.describe()

age       housing          loan      duration      campaign  \
count  29271.000000  29271.000000  29271.000000  29271.000000  29271.000000   
mean      40.126132      1.039903      0.325612    266.334973      2.737556   
std        9.522742      0.986956      0.721707    272.826726      3.085469   
min       17.000000      0.000000      0.000000      0.000000      1.000000   
25%       32.000000      0.000000      0.000000    103.000000      1.000000   
50%       39.000000      2.000000      0.000000    179.000000      2.000000   
75%       47.000000      2.000000      0.000000    327.000000      3.000000   
max       88.000000      2.000000      2.000000   4918.000000     56.000000   

              pdays    Subscribed  
count  29271.000000  29271.000000  
mean     988.235455      0.109187  
std      102.879851      0.311878  
min        0.000000      0.000000  
25%      999.000000      0.000000  
50%      999.000000      0.000000  
75%      999.000000      0.000000  
max      999.000000      1.000000

In [19]:
train_data.isnull().sum()

age           0
housing       0
loan          0
duration      0
campaign      0
pdays         0
Subscribed    0
dtype: int64

In [21]:
x= train_data.drop(columns="Subscribed")

In [23]:
y=train_data["Subscribed"]

In [25]:
from sklearn.model_selection import train_test_split

In [27]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.35,random_state=20)

In [29]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [31]:
x_train

age  housing  loan  duration  campaign  pdays
283     25        0     0      2203         2    999
11267   54        0     0       294         2    999
4162    46        0     0        93         1    999
17115   33        0     0       280         5    999
3990    26        0     0       416         2    999
...    ...      ...   ...       ...       ...    ...
23452   32        2     0       130         1    999
23775   49        2     0        60         1    999
4367    28        0     0       262         1    999
27098   55        0     0        63         2    999
15715   55        2     0       326         6    999

[19026 rows x 6 columns]

In [33]:
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [39]:
x_train_scaled

array([[-1.57849933, -1.05315187, -0.44907385,  7.06817719, -0.23767865,
         0.10665642],
       [ 1.44210636, -1.05315187, -0.44907385,  0.10076123, -0.23767865,
         0.10665642],
       [ 0.60883582, -1.05315187, -0.44907385, -0.63284307, -0.55875746,
         0.10665642],
       ...,
       [-1.26602288, -1.05315187, -0.44907385, -0.01603149, -0.55875746,
         0.10665642],
       [ 1.54626517, -1.05315187, -0.44907385, -0.74233624, -0.23767865,
         0.10665642],
       [ 1.54626517,  0.97183727, -0.44907385,  0.21755396,  1.04663659,
         0.10665642]])

In [41]:
x_test_scaled

array([[-1.26602288, -1.05315187, -0.44907385,  1.11174825, -0.55875746,
         0.10665642],
       [-1.05770525, -1.05315187, -0.44907385, -0.42115625,  0.08340016,
         0.10665642],
       [-1.47434052, -1.05315187, -0.44907385, -0.38465853, -0.55875746,
         0.10665642],
       ...,
       [ 0.50467701, -1.05315187, -0.44907385, -0.04522967, -0.23767865,
         0.10665642],
       [ 1.85874163,  0.97183727, -0.44907385,  0.12995941, -0.23767865,
         0.10665642],
       [-0.64106998,  0.97183727, -0.44907385, -0.5342992 ,  2.00987301,
         0.10665642]])

In [51]:
log_reg=LogisticRegression(random_state=0).fit(x_train_scaled,y_train)

In [55]:
log_reg.predict(x_train_scaled)

array([1, 0, 0, ..., 0, 0, 0], dtype=int8)

In [57]:
log_reg.score(x_train_scaled,y_train)

0.9112267423525702

In [59]:
log_reg.score(x_test_scaled,y_test)

0.9109809663250366